apiVersion: v1
kind: Service
metadata:
  name: clusterwatch-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: clusterwatch-agent
    app.kubernetes.io/component: collector
spec:
  selector:
    app.kubernetes.io/name: clusterwatch-agent
    app.kubernetes.io/component: collector
  ports:
    - name: http
      port: 8080
      targetPort: http
