{{- if .Values.addons.kubeStateMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterwatch-kube-state-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: clusterwatch-agent
    app.kubernetes.io/component: kube-state-metrics
{{- end }}
