apiVersion: v1
kind: Secret
metadata:
  name: clusterwatch-agent-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CLUSTERWATCH_EMAIL: {{ .Values.auth.email | quote }}
  CLUSTERWATCH_ACCESS_KEY: {{ .Values.auth.accessKey | quote }}
