apiVersion: v1
kind: Service
metadata:
  name: clustersage-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector: { app: clustersage-frontend }
  ports:
    - name: http
      port: 80
      targetPort: http
