{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.providerClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.vaultName | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
{{- range .Values.keyVault.objects }}
        - |
          objectName: {{ .name | quote }}
          objectType: secret
          objectAlias: {{ default .name .alias | quote }}
{{- end }}
{{- end }}
