{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: clustersage-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $k, $v := .Values.backend.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
