{{- if .Values.gateway.enabled }}
{{- $hostnames := default (list) .Values.gateway.hostnames }}
{{- if and (eq (len $hostnames) 0) .Values.gateway.hostname }}
{{- $hostnames = list .Values.gateway.hostname }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
{{ if gt (len $hostnames) 0 }}
{{ range $index, $hostname := $hostnames }}
    - name: http-{{ $index }}
      protocol: HTTP
      port: 80
      hostname: {{ $hostname | quote }}
      allowedRoutes:
        namespaces:
          from: All
{{ end }}
{{ else }}
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
{{ end }}
{{- end }}
