frontend:
  image:
    tag: "staging"
  replicaCount: 1
  env:
    NEXT_PUBLIC_API_URL: "https://stage.nexaflow.site"
backend:
  image:
    tag: "staging"
  replicaCount: 1
  env:
    APP_ENV: "staging"
    PUBLIC_APP_URL: "https://stage.nexaflow.site"
    PUBLIC_API_URL: "https://stage.nexaflow.site"
    CORS_ALLOWED_ORIGINS: "https://stage.nexaflow.site"
    AI_AGENT_ENABLED: "false"
emailWorker:
  image:
    tag: "staging"
  replicaCount: 1
gateway:
  hostname: "stage.nexaflow.site"
  hostnames:
    - "stage.nexaflow.site"
